### ISSUE TITLE
npm audit security report: High Insecure Cryptography Algorithm

### ISSUE THREAD

**Issue by almamlaka** [paulsutherland/polyonic-secure-pouch#1]
![Capture d’écran 2020-02-01 à 10 08 54](https://user-images.githubusercontent.com/59602921/73588495-ebeda200-44da-11ea-8d27-a8dcbab316ba.png)

[more info ](https://npmjs.com/advisories/1220)

**Comment by paulsutherland** [comment]
Updated dependencies
