### ISSUE TITLE
The replicate does not decrypt all docs in remote

### ISSUE THREAD

**Issue by daobuzhi** [paulsutherland/polyonic-secure-pouch#2]
as the doc says, "_If you replicate to another database, it will decrypt before sending it to the external one._ "

I tested it in following context, the result is tricky: some docs is decrypted, but others are still encrypted. 

environment:
pouchdb 7.1 
chrome 83 (dev)

when 
let source = PouchDB(dbInChrome); 
source.encrypt(passcode);

let target = PouchDB(remoteCouchDBURL);
PouchDB.replicate(source, target);

in target DB, some docs are still encrypted as that in source. 

appreciate for any idea and guide. 

Thanks

**Comment by paulsutherland** [comment]
@daobuzhi 

Could you perhaps be syncing docs that were created before you turned on/off remote encrypt.

Try a fresh db on both ends.

[Here is an example for you](https://github.com/paulsutherland/example-secure-pouchdb). I get consistent results.

If you still have issues - can you setup a demonstration so I can help further?

Cheers...

Paul
